### PR TITLE
Resolved issue #20

### PR DESCRIPTION
**Pull request by NgoQuocBao1010**
I think I solved the issue. Can you check it for me, please?

### CODE REVIEW

**Comment by piechowiakmichal** [comment]
Hi!

``Download CSV`` button works perfect, but ``Download JSON`` button does not work properly. 

When I want to download a JSON file while hosting a site locally, I get the following error:
```
This site can’t be reached

The webpage at file:///C:/Users/michael/Documents/Projects/Github/many-passwords.github.io/text/json;charset=utf-8,%5B%7B"Vendor"%3A"155"%2C"Model%2FSoftware%20name"%3A"CoreBuilder" [...]
might be temporarily down or it may have moved permanently to a new web address.

ERR_INVALID_URL
```
but when you do it when site is hosted on Github Page I am getting an ``network failed`` error. On every device, on every network.

In case of ``Passwords Count:``, you have to subtract 2.

The buttons are also not adapted to mobile devices, but I do not require it.

Can you fix it?

**Comment by NgoQuocBao1010** [comment]
> Hi!
> 
> `Download CSV` button works perfect, but `Download JSON` button does not work properly.
> 
> When I want to download a JSON file while hosting a site locally, I get the following error:
> 
> ```
> This site can’t be reached
> 
> The webpage at file:///C:/Users/michael/Documents/Projects/Github/many-passwords.github.io/text/json;charset=utf-8,%5B%7B"Vendor"%3A"155"%2C"Model%2FSoftware%20name"%3A"CoreBuilder" [...]
> might be temporarily down or it may have moved permanently to a new web address.
> 
> ERR_INVALID_URL
> ```
> 
> but when you do it when site is hosted on Github Page I am getting an `network failed` error. On every device, on every network.
> 
> In case of `Passwords Count:`, you have to subtract 2.
> 
> The buttons are also not adapted to mobile devices, but I do not require it.
> 
> Can you fix it, please?

Sure, I'll try fix it asap

**Comment by NgoQuocBao1010** [comment]
@piechowiakmichal Hi, I believe that the download JSON issue has been fixed, I also add some style to the button's layout for mobile friendly. Can you review it?

**Comment by piechowiakmichal** [comment]
@NgoQuocBao1010 works perfect! I will include you in the special thanks section in main repo. Thank you so much!

**Comment by NgoQuocBao1010** [comment]
@piechowiakmichal I'm sorry for the earlier bugs, I felt like I should have tested it more careful. Thanks for the opportunity, I'm super grateful that I can contribute to your project!

**Pull request merged**
